fruitsandjuice/urls.py
from django.urls import path, re_path

from fruitsandjuice.views import (
    ProductListView,
    AboutView,
    ShippayView,
    HomeRedirectView,
    RegistrationView,
    RegistrationSucessView,
    CartView,
    activate,
    OrderView,
    ProfileView,
    OrderSuccessfulView,
    logout, login_view, AddCartView, RemoveCartItemView)

app_name = 'fruitsandjuice'

urlpatterns = [
    path('', HomeRedirectView.as_view(), name='go_to_index'),
    path('logout/', logout, name='logout'),
    path('login/', login_view, name='login'),
    path('home/', ProductListView.as_view(), name='home'),
    path('about/', AboutView.as_view(), name='about'),
    path('shippay/', ShippayView.as_view(), name='shippay'),
    path('registration/', RegistrationView.as_view(), name='registration'),
    path('cart/', CartView.as_view(), name='cart'),
    path('cart/add/', AddCartView.as_view(), name='add_cart'),
    path('cart/remove/', RemoveCartItemView.as_view(), name='remove_cart'),
    path('order/<int:pk>/', OrderView.as_view(), name='order'),
    path('order_success/<int:pk>/', OrderSuccessfulView.as_view(), name='order_success'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('sucess_registration/', RegistrationSucessView.as_view(), name='success_registration'),
    re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
            activate, name='activate')
]

irina/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('fruitsandjuice.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fruitsandjuice/models.py
from enum import Enum

from django.db import models
from django.utils.safestring import mark_safe
from django.contrib.auth import get_user_model

# Create your models here.

User = get_user_model()


class PaymentMethodChoice(Enum):
    CH = 'Наличными'
    NCH = 'Безналичные'


class DeliveryMethodChoice(Enum):
    PU = 'Самовывоз'
    CR = 'Курьером'


class StatusChoice(Enum):
    FM = 'Формируется'
    ACP = 'Оформлен'
    INP = 'Собирается'
    RDY = 'Готов к выдаче'
    DTS = 'Отдан в службу доставки'
    CNC = 'Отменён'
    ISU = 'Выдан'


class Country(models.Model):
    name = models.CharField(verbose_name='Наименование', max_length=250)

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Страна'
        verbose_name_plural = 'Страны'


class ProductCategory(models.Model):
    name = models.CharField(verbose_name='Категория', max_length=25)
    anchor = models.CharField(verbose_name='Якорь для меню', max_length=10, blank=True, null=True)

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Product(models.Model):
    category = models.ForeignKey('ProductCategory', on_delete=models.CASCADE)
    name = models.CharField(verbose_name='Наименование', max_length=250)
    price = models.DecimalField(verbose_name='Цена', max_digits=8, decimal_places=2)
    country = models.ForeignKey(Country, null=True, blank=True, on_delete=models.SET_NULL)
    unit_product = models.ForeignKey('UnitsProduct', on_delete=models.CASCADE)
    sale = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'


class ProductImages(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField(verbose_name='Картинка', upload_to='product')
    alt = models.CharField(verbose_name='Alt', max_length=250, null=True, blank=True)

    def pre_image(self):
        return mark_safe(f'<img src="{self.image.url}" width="100" height="100" />')

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        if self.alt is None:
            self.alt = self.image.name
        super().save(force_insert=False, force_update=False, using=None, update_fields=None)

    def __str__(self):
        return f'{self.product.name} {self.image.url}'

    class Meta:
        verbose_name = 'Картинка'
        verbose_name_plural = 'Картинки'


class UnitsProduct(models.Model):
    name = models.CharField(verbose_name='Единица товара', max_length=25)
    packaging = models.CharField(verbose_name='Упаковка', default='1', max_length=25)

    def __str__(self):
        return f'{self.name} - {self.packaging}'

    class Meta:
        verbose_name = 'Единица товара'
        verbose_name_plural = 'Единицы товара'


class Order(models.Model):
    user_name = models.ForeignKey(User, on_delete=models.CASCADE)
    mobile = models.CharField(verbose_name='Моб. телефон', max_length=25)
    payment_method = models.CharField(verbose_name=('Способ оплаты'),
                                      max_length=3,
                                      choices=[(item.name, item.value) for item in PaymentMethodChoice],
                                      default=PaymentMethodChoice.CH.name)
    delivery_method = models.CharField(verbose_name=('Способ доставки'),
                                       max_length=3,
                                       choices=[(item.name, item.value) for item in DeliveryMethodChoice],
                                       default=DeliveryMethodChoice.CR.name)
    adress = models.CharField(verbose_name=('Адрес'), max_length=50, null=True, blank=True)
    status = models.CharField(verbose_name=('Статус'),
                              max_length=3,
                              choices=[(item.name, item.value) for item in StatusChoice],
                              default=StatusChoice.FM.name)

    def __str__(self):
        return f'{self.pk} {self.user_name}'

    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='products')

    def __str__(self):
        return f'id позиции: {self.pk} наименование: {self.product}'

    class Meta:
        verbose_name = 'Позиция'
        verbose_name_plural = 'Позиции заказа'

templates/fruitandjuice/about.html
{% extends 'base.html' %}
{% block menu %}
    {% include "fruitandjuice/menu.html" with active_tab='tab2' %}
{% endblock %}
{% block content %}
    <div class="container mt-7">
        <h2>Контактная информация</h2>
        <ul>
            <li>Телефон: <a href="tel:89260905545"></a>8(925)140-63-31</li>
            <li>E-mail: <a href="mailto:fresh-fruits@bk.ru"></a>fresh-fruits@bk.ru</li>
            <li>Instagram:</li>
            <li>Адрес: г. Москва ул. Трофимова д. 11</li>
            <script type="text/javascript" charset="utf-8" async
                    src="https://api-maps.yandex.ru/services/constructor/1.0/js/?um=constructor%3Ac3c4c87aa9df95f0fd504186ad2d22698c42ad09ff668ad3cd689b79d405e8d2&amp;width=758&amp;height=393&amp;lang=ru_RU&amp;scroll=true"></script>
        </ul>
        <h2>Реквизиты</h2>
        <ul>
            <li>ООО ГККМ (Группа компаний капитал маркет)</li>
            <li>ОГРН 114230801191</li>
            <li>ИНН 2308214369</li>
            <li>КПП 230801001</li>
        </ul>
    </div>
{% endblock %}

templates/fruitandjuice/cart.html
{% extends 'base.html' %}
{% block menu %}
    {% include "fruitandjuice/menu.html" with active_tab='' %}
{% endblock %}
{% block ext_menu %}
    {% include "fruitandjuice/ext_menu.html" with active_tab='ext_tab1' %}
{% endblock %}
{% block content %}
    <div class="container mt-7">
        {% if not cart_items %}
            <h2>Ваша корзина пуста</h2>
            <h4>Добавьте что-нибудь из <a href="{% url 'fruitsandjuice:home' %}">меню</a></h4>
        {% else %}
            <h2>Корзина</h2>
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th scope="col">№</th>
                    <th scope="col">Наименование продукта</th>
                    <th scope="col">Единица товара</th>
                    <th scope="col">Цена</th>
                    <th scope="col"></th>
                </tr>
                </thead>
                <tbody>
                {% for item in cart_items %}
                    <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td>{{ item.product.name }}</td>
                        <td>{{ item.product.unit_product }}</td>
                        <td>{{ item.product.price }} руб.</td>
                        <td align="center"><a href="{% url 'fruitsandjuice:cart' %}" value="{{ item.pk }}"
                                              class="btn prod_remove"><img class="fas fa-trash-alt fa-1x"></a></td>
                    </tr>
                {% endfor %}
                <tr>
                    <td colspan="3">Итого:</td>
                    <td>{{ summ_items.product__price__sum|floatformat:2 }} руб.</td>
                </tr>
                </tbody>
            </table>
            <form name="order" action="{% url 'fruitsandjuice:order' pk=pk_kart.pk %}" method="POST">
                {% csrf_token %}
                <div class="col-md-4 mb-3">
                    <h4 for="telephonenumber">Мобильный телефон:</h4>
                    <input name="mobile" type="text" class="form-control" id="telephonenumber" placeholder="9220005566"
                           value=""
                           required>
                </div>
                <div class="form-group col-md-5">
                    <h4 for="inputDelivery">Способ доставки:</h4>
                    <select required name="delivery_method" id="inputDelivery" class="form-control">
                        <option value="" selected>Выбирете способ доставки</option>
                        {% for ditem in delivery %}
                            <option value="{{ ditem.name }}">{{ ditem.value }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="col-md-5 mb-3 address d-none">
                    <h4 for="address">Адресс доставки:</h4>
                    <textarea name="address" type="text"
                              class="form-control" id="address" placeholder="Москва, ул. Новогордская, д 3, кв 5"
                              value="">

                </textarea>
                </div>
                <div class="form-group col-md-5">
                    <h4 for="inputPayment">Способ оплаты при получении:</h4>
                    <select required name="payment_method" id="inputPayment" class="form-control">
                        <option value="" selected>Выбирете способ оплаты</option>
                        {% for pitem in payment %}
                            <option value="{{ pitem.name }}">{{ pitem.value }}</option>
                        {% endfor %}
                    </select>
                </div>
                <button type="submit" class="btn btn-primary btn">Оформить</button>
            </form>
            <br>
        {% endif %}

    </div>
{% endblock %}

templates/fruitandjuice/ext_menu.html
{% if user.is_authenticated %}
    <a class="btn btn-primary {% if active_tab == 'ext_tab1' %} active{% endif %}"
       href="{% url 'fruitsandjuice:cart' %}" role="button"><img
            class="fas fa-shopping-cart fa-1x"><span id="cartspan" class="badge badge-pill badge-primary">{{ cart_count }}</span></a>
    <a class="btn btn-primary {% if active_tab == 'ext_tab2' %} active{% endif %}"
       href="{% url 'fruitsandjuice:profile' %}" role="button"
    >{{ user }}</a>
    <a class="btn btn-primary" href="{% url 'fruitsandjuice:logout' %}" role="button">
        Выйти
    </a>
{% else %}
    <button type="button" class="btn btn-primary" {% if active_tab == 'ext_tab2' %} active{% endif %}
            data-toggle="modal"
            data-target="#loginModalCenter">
        Войти
    </button>
    <button type="button" class="btn btn-primary" {% if active_tab == 'tab3' %} active{% endif %} data-toggle="modal"
            data-target="#regModalCenter">
        Зарегистрироваться
    </button>
{% endif %}

templates/fruitandjuice/home.html
{% extends 'base.html' %}
{% load static %}

{% block menu %}
    {% include "fruitandjuice/menu.html" with active_tab='tab1' %}
{% endblock %}

{% block content %}
    <div class="container mt-7">
        <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img src="{% static 'img/carousel/carouselfruits.jpg' %}" class="d-block w-3" alt="...">
                </div>
                <div class="carousel-item">
                    <img src="{% static 'img/carousel/carouseljuice.jpg' %}" class="d-block w-3" alt="...">
                </div>
                <div class="carousel-item">
                    <img src="{% static 'img/carousel/carouselmors.jpg' %}" class="d-block w-3" alt="...">
                </div>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
        <div>
            {% regroup products|dictsort:"category.pk" by category as category_list %}
            {% for category_item in category_list %}
                <h2 id="{{ category_item.grouper.anchor }}" class="mt-3 text-primary">{{ category_item.grouper }}</h2>
                <div class="row no-gutters">
                    {% for item in category_item.list %}
                        <div class="col-sm-6 col-md-4 col-lg-3 col-6 p-1">
                            <div class="card h-100 shadow-sm">
                                <img class="card-img-top"
                                     alt="{{ item.productimages_set.first.alt }}"
                                     src="{{ item.productimages_set.first.image.url }}" width="250">
                                <div class="card-body">
                                    <h4 class="card-title">{{ item.name }}</h4>
                                    <h5 class="card-text">Цена: {{ item.price }} руб. <br></h5>
                                    <h6> за {{ item.unit_product.packaging }} {{ item.unit_product.name }}</h6>
                                    {% if  item.country %}
                                        <h6> Страна: {{ item.country }}<h6>
                                    {% endif %}

                                    {% if user.is_authenticated %}

                                        <a href="#" value="{{ item.pk }}" class="btn btn-primary card_add">В
                                            КОРЗИНУ</a>
                                    {% else %}
                                        <a href="#" class="btn btn-primary card_add" data-toggle="modal"
                                           data-target="#loginModalCenter">В
                                            КОРЗИНУ</a>

                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            {% endfor %}
        </div>
    </div>
    <br>
{% endblock %}

templates/fruitandjuice/mail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% autoescape off %}
    Hi {{ user.username }},
    Please click on the link to confirm your registration,
    http://{{ domain }}{% url 'fruitsandjuice:activate' uidb64=uid token=token %}
    {% endautoescape %}
</body>
</html>

templates/fruitandjuice/menu.html
<ul class="topmenu navbar-nav btn-group" role="group" aria-label="Basic example">
    <li class="nav-item dropdown m-1">
        <a class="dropdown-toggle btn btn-primary {% if active_tab == 'tab1' %} active{% endif %}"
           href="#"
           id="asortiDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Меню</a>
        <div class="dropdown-menu" aria-labelledby="asortiDropdown">
            {% for item in categories_menu %}
                <a class="dropdown-item" href="{% url 'fruitsandjuice:home' %}#{{ item.anchor }}">{{ item.name }}</a>
            {% endfor %}
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url 'fruitsandjuice:home' %}">Распродажа</a>

        </div>
    </li>
    <li class="nav-item m-1">
        <a class="btn btn-primary {% if active_tab == 'tab2' %} active{% endif %}"
           href="{% url 'fruitsandjuice:about' %}">О Нас</a>
    </li>
    <li class="nav-item m-1">
        <a class="btn btn-primary {% if active_tab == 'tab3' %} active{% endif %}"
           href="{% url 'fruitsandjuice:shippay' %}">Доставка и оплата</a>
    </li>
</ul>

templates/fruitandjuice/order_success.html
{% extends 'base.html' %}
{% block menu %}
    {% include "fruitandjuice/menu.html" with active_tab='' %}
{% endblock %}
{% block ext_menu %}
    {% include "fruitandjuice/ext_menu.html" with active_tab='ext_tab1' %}
{% endblock %}
{% block content %}
    <div class="container mt-7">
        <h4>Ура! Ваш заказ № {{ pk }} оформлен. Скоро для подтверждения с Вами свяжется наш менеджер. Статус заказа можно посмотреть в <a href="{% url 'fruitsandjuice:profile' %}">профиле</a></h4>
        <h4>Можете продолжить свои покупки и добавть позиции товаров из <a href="{% url 'fruitsandjuice:home' %}">меню</a></h4>
    </div>
{% endblock %}

templates/fruitandjuice/profile.html
{% extends 'base.html' %}
{% block menu %}
    {% include "fruitandjuice/menu.html" with active_tab='' %}
{% endblock %}
{% block ext_menu %}
    {% include "fruitandjuice/ext_menu.html" with active_tab='ext_tab2' %}
{% endblock %}
{% block content %}
    <div class="container mt-7">
        {% if not orders %}
            <h2>У Вас еще нет заказов.</h2>
            <h4>Добавьте что-нибудь из <a href="{% url 'fruitsandjuice:home' %}">меню</a></h4>
        {% else %}
            <h2>Заказы</h2>
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th scope="col">№ заказа</th>
                    <th scope="col">Мобильный тел.</th>
                    <th scope="col">Статус</th>
                    <th scope="col">Способ доставки</th>
                </tr>
                </thead>
                <tbody>
                {% for item in orders %}
                    <tr>
                        <th scope="row">{{ item.pk }}</th>
                        <td>{{ item.mobile }}</td>
                        <td>{{ item.get_status_display }}</td>
                        <td>{{ item.get_delivery_method_display }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        {% endif %}
    </div>
{% endblock %}

templates/fruitandjuice/shippay.html
{% extends 'base.html' %}
{% block menu %}
    {% include "fruitandjuice/menu.html" with active_tab='tab3' %}
{% endblock %}
{% block content %}
    <div class="container mt-7">
        <h2>Условия доставки </h2>
        <p>Уважаемые покупатели, ознакомьтесь с условиями доставки и способами оплаты товара, так Вы получите ответы на
            многие вопросы.</p>
        <h3>Оформление и обработка заказов</h3>
        <p>Мы рады, что Вы выбрали нашу компанию! Поэтому, как только мы получим уведомление о поступившем заказе,
            начнем собирать его у себя на складе. Если необходимого товара нет у нас на складе, наш менеджер свяжется с
            Вами (WhatsApp или по телефону) и оговорит сроки и дату поступления товара. Обычно доставка по Москве
            осуществляется в течение 1 рабочего дня. Пожалуйста указывайте действующий номер телефона, мы доставляем
            товар только после предварительного с Вами согласования.
        </p>
        <h3>Способы оплаты</h3>
        <p>Наличный расчет. Оплата курьеру при получении. С этим все просто: наш курьер приезжает к Вам, Вы проверяете
            товар, получаете и передаете ему деньги. <br>
            Оплата картой (по терминалу). Оплата по терминалу возможна при самовывозе, а также при предварительном
            согласовании с менеджером. Во время оформления заказа Вы говорите, что будете расплачиваться по карте, мы
            согласовываем и отправляем к Вам курьера с терминалом. <br>
            Банковский перевод для юридических лиц и предпринимателей. Мы выставляем и отправляем счет на оплату, вы
            оплачиваете и уведомляете нас об этом любым удобным способом. Когда денежные средства поступят на наш
            расчетный счет, доставка будет осуществлена в течение суток. Обратите внимание, что при оплате банковским
            переводом возможны дополнительные сборы банком. Пакет документов для бухгалтерии Вы получаете вместе с
            заказом.
        </p>
        <h3>Способы доставки</h3>
        <p>Курьером по Москве и Московской области <br>
            Самовывоз из распределительного центра (по предварительному заказу)
        </p>
        <h4>Стоимость доставки в пределах МКАД</h4>
        <p>500 рублей; <br>
            Заказ на сумму более 3000 рублей доставка без доплаты. <br>
            Доставка заказов осуществляется во временной интервал с 09:00 до 23:00 (точное время доставки оговаривается
            при заказе).
        </p>
        <h4>Стоимость доставки по Московской области</h4>
        <p>Стоимость доставки в радиусе 10-20 км от МКАД составляет до 1000 рублей (предварительно оговаривается
            индивидуально).</p>
        <h4>Доставка транспортной компанией</h4>
        <p>Стоимость доставки зависит от адреса поставки. Доставка осуществляется при 100% предоплате. Расходы за
            доставку оплачивает покупатель. </p>
    </div>
{% endblock %}

templates/fruitandjuice/success_registration.html
{% extends 'base.html' %}
{% block menu %}
    {% include "fruitandjuice/menu.html" with active_tab='tab1' %}
{% endblock %}
{% block content %}
    <div class="container mt-7">
        <h4>Ура, {{ user }}! Ваша регистрация прошла успешно.</h4>
    </div>
{% endblock %}